# Generated by Django 4.0 on 2023-02-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetsQuiz_Api', '0002_jwt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizequiz',
            name='proctoring',
        ),
        migrations.AddField(
            model_name='organizequiz',
            name='students',
            field=models.IntegerField(default=0),
        ),
    ]
