# Generated by Django 4.0 on 2023-02-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetsQuiz_Api', '0003_remove_organizequiz_proctoring_organizequiz_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizequiz',
            name='quid_title',
            field=models.CharField(default='Quiz-<django.db.models.fields.IntegerField>', max_length=255),
        ),
    ]
