# Generated by Django 4.0 on 2023-02-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LetsQuiz_Api', '0004_organizequiz_quid_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizequiz',
            old_name='quid_title',
            new_name='quiz_title',
        ),
    ]
