# Generated by Django 4.0 on 2023-02-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetsQuiz_Api', '0005_rename_quid_title_organizequiz_quiz_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizequiz',
            name='quiz_title',
            field=models.CharField(default='Quiz-<django.db.models.fields.IntegerField>', max_length=255, unique=True),
        ),
    ]
