# Generated by Django 4.0 on 2023-02-16 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_alter_user_email'),
        ('LetsQuiz_Api', '0006_alter_organizequiz_quiz_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_user', to='auth.user'),
        ),
    ]
