# Generated by Django 4.0 on 2023-02-16 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_alter_user_email'),
        ('LetsQuiz_Api', '0007_alter_jwt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwt',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_user', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='organizequiz',
            name='organiser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
