# Generated by Django 4.0 on 2023-02-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetsQuiz_Api', '0008_alter_jwt_user_alter_organizequiz_organiser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizequiz',
            name='past',
            field=models.BooleanField(default=False),
        ),
    ]
