# Generated by Django 4.0 on 2023-02-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetsQuiz_Api', '0009_organizequiz_past'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinquiz',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
